import { ReactNode } from "react";
import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const RootClientComponent = dynamic(() => import("./client"));
const Canvas = dynamic(() => import("@/components/atoms/canvas"));
const Navbar = dynamic(() => import("@/components/organisms/navbar"));

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <RootClientComponent>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} font-geistSans antialiased`}
        >
          <Canvas />
          <Navbar />
          <main className="layout">{children}</main>
        </body>
      </html>
    </RootClientComponent>
  );
}
